apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api
  namespace: 12-factor-app
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: api
  namespaceSelector:
    matchNames:
      - 12-factor-app
  endpoints:
  - port: metrics # Here we use the name of the port defined earlier