prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'traefik'
        kubernetes_sd_configs:
          - role: pod
            selectors:
              - role: pod
                label: "app.kubernetes.io/instance=traefik"
                containers:
                  traefik:
                    ports: 9100
      - job_name: '12-factor-app/api'
        scrape_interval: 5s
        static_configs:
        - targets: [api.12-factor-app.svc.cluster.local:3030]
          labels:
            app: api
            port: 3030
    retention: 3d