apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: chaos-on-the-rise
  namespace: chaos-testing
spec:
  entry: entry
  templates:
    - name: entry
      templateType: Serial
      deadline: 1h
      children:
        - mongo-and-app-fail
        - mongo-io-lossy
    - name: app-network-loss
      templateType: NetworkChaos
      deadline: 10m
      networkChaos:
        selector:
          namespaces:
            - 12-factor-app
          labelSelectors:
            app: api
        mode: all
        action: loss
        loss:
          loss: '10'
        direction: to
    - name: pod-failure-mongo
      templateType: PodChaos
      deadline: 10m
      podChaos:
        selector:
          namespaces:
            - 12-factor-app
          labelSelectors:
            app: mongo
        mode: all
        action: pod-failure
    - name: mongo-and-app-fail
      templateType: Parallel
      deadline: 20m
      children:
        - app-network-loss
        - pod-failure-mongo
    - name: mongo-io-lossy
      templateType: IOChaos
      deadline: 10m
      ioChaos:
        selector:
          namespaces:
            - 12-factor-app
          labelSelectors:
            app: mongo
        mode: all
        action: latency
        delay: 10ms
        percent: 100
        volumePath: "/data/db"