apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: logging
spec:
  version: 8.1.2
  count: 1 # Elastic Search statefulset deployment with one replicas
  elasticsearchRef:
    name: "efk"
  http:  # NOTE disabling kibana automatic TLS configuration
    tls:
      selfSignedCertificate:
        disabled: true