provisionDataStore:
  cassandra: false
allInOne:
  enabled: true
  extraEnv:
    - name: QUERY_BASE_PATH
      value: /jaeger
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 256m
      memory: 128Mi
storage:
  type: none
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false