kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: default
  name: account-default-viewer-qjvha

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: role-default-viewer-qjvha
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups:
  - chaos-mesh.org
  resources: [ "*" ]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-default-viewer-qjvha
  namespace: default
subjects:
- kind: ServiceAccount
  name: account-default-viewer-qjvha
  namespace: default
roleRef:
  kind: Role
  name: role-default-viewer-qjvha
  apiGroup: rbac.authorization.k8s.io

