apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: burn-cpu-100
  namespace: chaos-testing
spec:
  mode: one
  selector:
    namespaces:
      - 12-factor-app
    labelSelectors:
      "app": "products"
  stressors:
    cpu:
      workers: 1
      load: 100
  duration: "30s"
