apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-corrupt-example
  namespace: chaos-testing
spec:
  action: corrupt
  mode: one
  selector:
    namespaces:
      - 12-factor-app
    labelSelectors:
      "app": "api"
  corrupt:
    corrupt: "40"
    correlation: "25"
  duration: "10s"
