apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: scheduled-pod-failure-app
spec:
  schedule: "5 * * * *"
  historyLimit: 2
  concurrencyPolicy: "Allow"
  type: "PodChaos"
  podkChaos:
    action: pod-failure
    mode: one
    selector:
      namespaces:
        - 12-factor-app
      labelSelectors:
        "app": "api"
    delay:
      latency: "10ms"
      correlation: "100"
      jitter: "0ms"
    duration: "12s"
