# apiVersion: opentelemetry.io/v1alpha1
# kind: OpenTelemetryCollector
# metadata:
#   name: otel-collector
#   namespace: opentelemetry-operator-system
#   labels:
#     app: opentelemetry
#     component: otel-collector
# spec:
#   mode: deployment
#   config: |
#     receivers:
#       otlp:
#         protocols:
#           grpc:
#           http:
#     exporters:
#       jaeger:
#         endpoint: "http://simplest-collector.deafault.svc.cluster.local:14250"
#         tls:
#           insecure: true
#       logging:
#     service:
#       telemetry:
#         logs:
#           level: "debug"
#       pipelines:
#         traces:
#           receivers: [otlp]
#           processors: []
#           exporters: [logging, jaeger]
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: opentelemetry-operator-system
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      jaeger:
        endpoint: "simplest-collector.default.svc.cluster.local:14250"
        tls:
          insecure: true
      logging:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging, jaeger]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging]