apiVersion: v1
kind: Namespace
metadata:
  name: 12-factor-app
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: nodejs-instrumentation
  namespace: 12-factor-app
spec:
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: always_on
  nodejs: