apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
   additionalArguments:
     - "--accesslog"
     - "--metrics.prometheus.buckets=0.100000, 0.300000, 1.200000, 5.000000"
     - "--metrics.prometheus.addEntryPointsLabels=true"
     - "--metrics.prometheus.addServicesLabels=true"
    #  - "--tracing.jaeger=true"
    #  - "--tracing.serviceName=traefik"
    #  - "--tracing.jaeger.samplingServerURL=http://simplest-agent.default.svc:5778/sampling"
    #  - "--tracing.jaeger.localAgentHostPort=simplest-agent.default.svc:6831"