apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
   podAnnotations:
     sidecar.jaegertracing.io/inject: "true"
   additionalArguments:
     - "--metrics.prometheus.buckets=0.100000, 0.300000, 1.200000, 5.000000"
     - "--metrics.prometheus.addEntryPointsLabels=true"
     - "--metrics.prometheus.addServicesLabels=true"
     - "--tracing.jaeger=true"
     - "--tracing.jaeger.samplingServerURL=http://127.0.0.1:5778/sampling"
     - "--tracing.jaeger.samplingType=const"
     - "--tracing.jaeger.samplingParam=1.0"
     - "--tracing.jaeger.localAgentHostPort=127.0.0.1:6831"
     - "--tracing.jaeger.propagation=jaeger"
     - "--tracing.jaeger.traceContextHeaderName=uber-trace-id"