apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server-elastic
  namespace: default
spec:
  version: 8.8.1
  count: 1
  http:
    tls:
      selfSignedCertificate:  ### disable tls will be easy for test
        disabled: true        ### not recommend for production
  elasticsearchRef:
    name: "elasticsearch"
  kibanaRef:
    name: "kibana"
  #config:
  #  output:
  #    elasticsearch:
  #      hosts: ["elasticsearch-es-http.default.svc:9200"]
