apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server-staging
  namespace: logging
spec:
  version: 7.12.0 ### define the version
  count: 1
  http:
    tls:
      selfSignedCertificate:  ### disable tls will be easy for test
        disabled: true        ### not recommend for production
  config:
    apm-server:
      capture_personal_data: true
    instrumentation:
      enabled: true
    output:
      elasticsearch:
        hosts: ["efk-es-http.logging.svc.cluster.local:9200"]
    logging.level: info ### enable logging for debug
    logging.to_stderr: true ### output error if any
    logging.metrics.enabled: true