# fluentbit helm chart values

#fluentbit-container environment variables:
env:
# Elastic operator creates elastic service name with format cluster_name-es-http
- name: FLUENT_ELASTICSEARCH_HOST
  value: "efk-es-http"
# Default elasticsearch default port
- name: FLUENT_ELASTICSEARCH_PORT
  value: "9200"
# Elasticsearch user
- name: FLUENT_ELASTICSEARCH_USER
  value: "elastic"
# Elastic operator stores elastic user password in a secret
- name: FLUENT_ELASTICSEARCH_PASSWORD
  valueFrom:
    secretKeyRef:
      name: "efk-es-elastic-user"
      key: elastic
# Specify TZ
- name: TZ
  value: "Europe/Madrid"
# Fluentbit config
config:
  # Helm chart combines service, inputs, outputs, custom_parsers and filters section
  # fluent-bit.config SERVICE
  service: |

    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On
        storage.path /var/log/fluentbit/storage
        storage.sync normal
        storage.checksum off
        storage.backlog.mem_limit 5M
        storage.metrics on

  # fluent-bit.config INPUT:
  inputs: |

    [INPUT]
        Name tail
        Alias input.kube
        Path /var/log/containers/*.log
        Path_Key filename
        multiline.parser docker, cri
        DB /var/log/fluentbit/flb_kube.db
        Tag kube.*
        Mem_Buf_Limit 5MB
        storage.type filesystem
        Skip_Long_Lines On

    [INPUT]
        Name tail
        Alias input.host
        Tag host.*
        DB /var/log/fluentbit/flb_host.db
        Path /var/log/auth.log,/var/log/syslog,/var/log/containers
        Path_Key filename
        Mem_Buf_Limit 5MB
        storage.type filesystem
        Parser syslog-rfc3164-nopri

  # fluent-bit.config OUTPUT
  outputs: |

    [OUTPUT]
        Name es
        match *
        Host ${FLUENT_ELASTICSEARCH_HOST}
        Port ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format True
        Logstash_Prefix logstash
        Suppress_Type_Name True
        Include_Tag_Key True
        Tag_Key tag
        HTTP_User ${FLUENT_ELASTICSEARCH_USER}
        HTTP_Passwd ${FLUENT_ELASTICSEARCH_PASSWORD}
        tls False
        tls.verify False
        Retry_Limit False
        Replace_Dots On

  # fluent-bit.config PARSERS:
  customParsers: |

    [PARSER]
        Name syslog-rfc3164-nopri
        Format regex
        Regex /^(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$/
        Time_Key time
        Time_Format %b %d %H:%M:%S
        Time_Keep Off

  # fluent-bit.config FILTERS:
  filters: |
    [FILTER]
        name                  multiline
        match                 *
        multiline.key_content log
        multiline.parser      java,python,go

    [FILTER]
        Name kubernetes
        Match kube.*
        Buffer_Size 512k
        Kube_Tag_Prefix kube.var.log.containers.
        Merge_Log On
        Merge_Log_Trim Off
        Merge_Log_Key log_processed
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        Annotations Off
        Labels On

    [FILTER]
        Name modify
        Match kube.*
        Remove _p
        Rename log message

    [FILTER]
        Name lua
        Match host.*
        script /fluent-bit/scripts/adjust_ts.lua
        call local_timestamp_to_UTC
  # json-exporter config
  extraFiles:
    json-exporter-config.yml: |
      modules:
        default:
          metrics:
            - name: fluenbit_storage_layer
              type: object
              path: '{.storage_layer}'
              help: The total number of chunks in the fs storage
              values:
                fs_chunks_up: '{.chunks.fs_chunks_up}'
                fs_chunks_down: '{.chunks.fs_chunks_down}'

# Fluentbit config Lua Scripts.
luaScripts:
  adjust_ts.lua: |
    function local_timestamp_to_UTC(tag, timestamp, record)
        local utcdate   = os.date("!*t", ts)
        local localdate = os.date("*t", ts)
        localdate.isdst = false -- this is the trick
        utc_time_diff = os.difftime(os.time(localdate), os.time(utcdate))
        return 1, timestamp - utc_time_diff, record
    end

# Enable fluentbit instalaltion on master node.
tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule

# Init container. Create directory for fluentbit
initContainers:
  - name: init-fluentbit-directory
    image: busybox
    command: ['/bin/sh', '-c', 'if [ ! -d /var/log/fluentbit ]; then mkdir -p /var/log/fluentbit; fi ; if [ ! -d /var/log/fluentbit/tail-db ]; then mkdir -p /var/log/fluentbit/tail-db; fi ; if [ ! -d /var/log/fluentbit/storage ]; then mkdir -p /var/log/fluentbit/storage; fi']
    volumeMounts:
      - name: varlog
        mountPath: /var/log
# Sidecar container to export storage metrics
extraContainers:
  - name: json-exporter
    image: quay.io/prometheuscommunity/json-exporter
    command: ['/bin/json_exporter']
    args: ['--config.file=/json-exporter-config.yml']
    ports:
      - containerPort: 7979
        name: http
        protocol: TCP
    volumeMounts:
      - mountPath: /json-exporter-config.yml
        name: config
        subPath: json-exporter-config.yml